name: Build

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./gradlew build
 
      - uses: actions/upload-artifact@v1
        with:
          name: GroundStation
          path: build/libs/GroundStation.jar
      
      - name: Create directories
        run: mkdir -p builds/october-sky/data builds/hotfire-test/data
      - name: Copy kml file
        run: cp _GoogleEarthView.kml builds/october-sky/_GoogleEarthView.kml; cp _GoogleEarthView.kml builds/hotfire-test/_GoogleEarthView.kml;
      - name: Copy jar file
        run: cp build/libs/GroundStation.jar builds/october-sky/GroundStation.jar; cp build/libs/GroundStation.jar builds/hotfire-test/GroundStation.jar
        
      - uses: actions/upload-artifact@v1
        with:
          name: GroundStationWithHotfireConfig.zip
          path: builds/hotfire-test