name: Test

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./gradlew test